title: <p align="center"> Vipul Fande </p>
logo : <center><img src="assets/img/pic_edited.jpg"/></center>


description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/vipul-fande-219797147/">LinkedIn</a> |
  <a href="https://github.com/vips0581">GitHub</a>
  
  <br>   
  I'm working on Fraud Detection and compliance related java based tool .
  Also handing the Big Data from real-time Ad call data.
  Working in Fintech domain for 6 years.
  <br>
  </p>



theme: jekyll-theme-minimal
